### ISSUE TITLE
Remove events

### ISSUE THREAD

**Issue by romkatsu** [yiisoft/yii-queue#113]
There are no cases of using the event, except for metrics (they can be configured by other means), we decided to delete them.

**Comment by luke-** [comment]
@romkatsu Just curious: About which event is it about?

**Comment by samdark** [comment]
All queue-related events. These were meant for monitoring purposes like building a dashboard but that could be done better with, for example, decorators.

**Comment by samdark** [comment]
@luke- do you have more use-cases for these?

**Comment by luke-** [comment]
@samdark There is probably a nicer solution for this without events: 

We had an event type that should not be queued multiple times at the same time. For this we have implemented a filter via events. e.g. https://github.com/humhub/humhub/blob/master/protected/humhub/modules/queue/Events.php#L57

**Comment by samdark** [comment]
Well... mutex?

**Comment by luke-** [comment]
This could prevent a simultaneous processing of the event.

But in our case it is more about the fact that it should not really be queued multiple times. Independent of the adapter.

**Comment by romkatsu** [comment]
I think that the logic of adding to the queue should not be based on events. I am generally against building logic on events. It's implicit and growing fast.

**Comment by samdark** [comment]
@luke- it's not ideal but:

1. You'll need shared persistence storage such as Redis since there are many workers and many main processes that could put jobs into queue.
2. Before putting job into queue we check storage for job ID. If it is there, skipping. If not, adding job to queue and writing job key to the storage.
3. In the job itself right at the end we remove job ID from the storage.

The disadvantage here is that you need to customize the job itself.

**Comment by luke-** [comment]
@samdark Thanks for the thoughts. That's right, that way it could work without events.... Maybe somehow also in combination with Behaviors.

**Comment by viktorprogger** [comment]
@luke-, looks like #116 is something you would like to use for this functionality.
