### ISSUE TITLE
Remove QueueInterface

### ISSUE THREAD

**Issue by viktorprogger** [yiisoft/yii-queue#149]
Fix config and tests accordingly.

**Comment by viktorprogger** [comment]
@xepozz Check please if we still can remove this interface after #154.

**Comment by xepozz** [comment]
What's the reason to delete this one and #150 ?

**Comment by xepozz** [comment]
No, they doesn't. 
You may think so because the `QueueInterface` has many mixed methods like `push`, `listen`, `run` and so on.
Just split some of them or just remove from the interface.

Let's decompose it
Queue:
- push(message): message (stamped with id)
- pop(): message
- status(id): status

I'd suggest to remove all of these methods and move them either to configuration layer (preferable way as for me) or new interface that extends the main one:
- withChannel
- getChannel
- withAdapter

And the last one thing is the second argument of current `push` method:
- middlewares for the push command
I don't really think it should be here. Create some decorator over `MessageInterface` or add middlewares as an argument of `Message` classes, or move them to configuration layer. The last is also preferable way as for me.

So that's the tree how it may look like:

Queues:
- post.like.added
- post.like.removed

Middlewares:
- post.like.added
  - consuming middlewares
    - Set request-id from the message
    - Hydrate data
    - Check checksum
    - Log into db
  - pushing middlewares:
    - Add timestamp
    - Pass request-id from the http request headers
    - Log into db
    - Do something custom
- ...

So you cannot change the middleware stack while you use a queue. If you want to change it, it should be another usecase of your queue

Usage:
```php
class Controller
{
    public function __construct(
        private QueueFactory $queueFactory,
    ) {
    }

    public function someAction()
    {
        $queue = $this->queueFactory->create('post.like.added');
        $queue->push(new Message([
            'id' => 1,
            'time' => time(),
            'user_id' => 1,
        ]));
        // or 
        $queue = $this->queueFactory->create('post.like.removed');
        $queue->push(new Message([
            'id' => 1,
            'time' => time(),
            'user_id' => 1,
        ]));
    }
}
```

Or if you like to use the queues without factories
```php
class Controller
{
    public function __construct(
        private QueueInterface $addLikeQueue,
        private QueueInterface $removeLikeQueue,
    ) {
    }

    public function someAction()
    {
        $this->addLikeQueue->push(new Message([
            'id' => 1,
            'time' => time(),
            'user_id' => 1,
        ]));
        // or
        $this->removeLikeQueue->push(new Message([
            'id' => 1,
            'time' => time(),
            'user_id' => 1,
        ]));
        // so if you need to check status of the processing:
        sleep(1);

        if ($this->removeLikeQueue->status($message)->isDone()) {
            // ...
        }
    }
}
```

These are use-cases of the most frequent usage the queue.

Going further.
Listening and running.

It's not queue's responsibility because queues are just storages. It should be separated. 
If you look at https://github.com/yiisoft/yii-queue/blob/26c7d7a96fbeda4dc40c6a72e37f354b6157a69d/src/Debug/QueueDecorator.php#L21-L36 you may see that useful payload only from push and status methods.

So if you were inspired to improve the queue interface the best way if decompose it.

**Comment by viktorprogger** [comment]
Thank you very much for your detailed suggestions. As for now I don't see how it could be implemented.  
According to the main issue topic: we will not remove the `QueueInterface`.

**Comment by viktorprogger** [comment]
A few more words about the second parameter of the `push` method.  
There are some cases when one should push message to a queue channel with a variable postponement (or even without it), which depends on the current system state.

**Comment by xepozz** [comment]
There are still different queues.
